'use strict';
const $=id=>document.getElementById(id), canvas=$('card'), ctx=canvas.getContext('2d');
const mono='"D2Coding", monospace', sans=mono;
const emptyImage=()=>({img:null,src:'',zoom:1,dx:0,dy:0,title:'',caption:'',showCaption:true});
const THEMES=[
{id:'cyan',name:'CYAN LINK',label:'시안 링크',accent:'#52ded3',bg1:'#081c21',bg2:'#02090d'},
{id:'crimson',name:'RED PROTOCOL',label:'레드 프로토콜',accent:'#ff515a',bg1:'#200d17',bg2:'#09070d'},
{id:'cobalt',name:'DEEP BLUE',label:'딥 블루',accent:'#6eacff',bg1:'#0b1c38',bg2:'#040914'},
{id:'amber',name:'AMBER CORE',label:'앰버 코어',accent:'#ffc367',bg1:'#261c12',bg2:'#0c0c0b'},
{id:'silver',name:'SILVER SHELL',label:'실버 셸',accent:'#51566d',bg1:'#eef0f4',bg2:'#cdd3df'},
{id:'mono',name:'GHOST SIGNAL',label:'고스트 시그널',accent:'#d6dbe3',bg1:'#1a1d25',bg2:'#080a0d'}
];
let palette;
function colors(){const hex=state.bg1.slice(1);const rgb=[0,2,4].map(i=>parseInt(hex.slice(i,i+2),16));const light=(rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722)>155;return light?{light,ink:'#202838',text:'#354155',muted:'#59677d',dim:'#737e91',line:'#8e9aae',surface:'#d5dce6',panel:'#ffffff48',grid:'#35415510'}:{light,ink:'#e4f1f5',text:'#b2c7d1',muted:'#7b9ba9',dim:'#4e727f',line:'#335361',surface:'#08141c',panel:'#b0deee06',grid:'#79d9e90b'}}
function applyTheme(id){const t=THEMES.find(t=>t.id===id)||THEMES[0];Object.assign(state,{theme:t.id,accent:t.accent,bg1:t.bg1,bg2:t.bg2});syncFields()}
function updateChrome(){palette=colors();const root=document.documentElement.style;root.setProperty('--accent',state.accent);root.setProperty('--studio-bg',state.bg2);root.setProperty('--studio-panel',state.bg1);root.setProperty('--text',palette.ink);root.setProperty('--muted',palette.muted);root.setProperty('--line',palette.line);root.setProperty('--control-bg',palette.light?'#f7f8fb':'#070e14');root.setProperty('--control-text',palette.ink);document.body.classList.toggle('light-theme',palette.light)}
function renderThemes(){const root=$('theme-presets');root.replaceChildren();THEMES.forEach(t=>{const active=state.theme===t.id&&state.accent===t.accent&&state.bg1===t.bg1&&state.bg2===t.bg2;const b=el('button',{class:'theme-preset'+(active?' active':''),'aria-pressed':active,'aria-label':t.label+' 테마 적용'});b.style.setProperty('--t-accent',t.accent);b.style.setProperty('--t-start',t.bg1);b.style.setProperty('--t-end',t.bg2);const preview=el('span',{class:'theme-mini','aria-hidden':'true'});preview.append(el('i'),el('i'),el('i'));b.append(preview,el('span',{class:'theme-name'},t.name),el('small',{},t.label));b.onclick=()=>applyTheme(t.id);root.append(b)})}
const initial=()=>({name:'YOUR NAME',handle:'@your_id',tagline:'취향과 이야기를 이곳에 기록합니다.',contact:'연락은 DM 또는 멘션으로 받습니다.',farewell:'재연결 가능합니다.',genre:'',info:'좋아하는 이야기를 나눕니다.\n서로의 취향을 존중합니다.',ng:'서로의 경계를 존중합니다.',galleryTitle:'좋아하는 것들',credit:'',theme:'cyan',accent:'#52ded3',bg1:'#081c21',bg2:'#02090d',layout:'landscape',grid:true,mono:false,fontScale:100,avatar:emptyImage(),gallery:[emptyImage(),emptyImage()],stickers:[],groups:[{id:'age',label:'연령',single:true,options:['성인','미성년','비공개'],selected:['비공개']},{id:'tweet',label:'트윗 성향',options:['RT','마음','소비','연성','탐라대화','일상','드림'],selected:['마음','일상']},{id:'leave',label:'이별 시',options:['블락','블언블','뮤트'],selected:['블언블']}]});
let state=initial(),hits=[],W=1200,H=760,currentTab='profile',pendingUpload=null,drag=null,toastTimer;
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3000)}
function tab(name){currentTab=name;document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===name);b.setAttribute('aria-pressed',b.dataset.tab===name)});['profile','images','style','stickers'].forEach(t=>$('panel-'+t).hidden=t!==name)}
function setLayout(layout){state.layout=layout;document.querySelectorAll('[data-layout]').forEach(b=>{b.classList.toggle('selected',b.dataset.layout===layout);b.setAttribute('aria-pressed',b.dataset.layout===layout)});$('canvas-wrap').classList.toggle('portrait',layout==='portrait');$('layout-label').textContent=layout.toUpperCase();draw()}
function syncFields(){for(const k of ['name','handle','tagline','contact','farewell','genre','info','ng','galleryTitle','credit','fontScale'])$(k).value=state[k];for(const k of ['accent','bg1','bg2']){$(k).value=state[k];$(k+'-hex').value=state[k].toUpperCase()}$('grid').checked=state.grid;$('mono').checked=state.mono;$('font-value').value=state.fontScale+'%';updateChrome();renderThemes();setLayout(state.layout);renderTags();renderImages();renderStickers()}
function el(tag,attrs={},text){const e=document.createElement(tag);for(const [k,v]of Object.entries(attrs)){if(k==='class')e.className=v;else if(k==='onClick')e.onclick=v;else e.setAttribute(k,v)}if(text!==undefined)e.textContent=text;return e}
function renderTags(){const root=$('tag-controls');root.replaceChildren();state.groups.forEach(g=>{const section=el('div');section.append(el('div',{class:'tag-label'},g.label+(g.single?' · 하나 선택':'')));const chips=el('div',{class:'chips'});g.options.forEach(t=>{const b=el('button',{class:'chip'+(g.selected.includes(t)?' on':''),'aria-pressed':g.selected.includes(t)},t);b.onclick=()=>{if(g.single)g.selected=g.selected.includes(t)?[]:[t];else g.selected=g.selected.includes(t)?g.selected.filter(x=>x!==t):[...g.selected,t];renderTags();draw()};chips.append(b)});section.append(chips);if(!g.single){const row=el('form',{class:'tag-add'}),input=el('input',{placeholder:'직접 입력',maxlength:'10','aria-label':g.label+' 태그 추가'}),button=el('button',{type:'submit','aria-label':'태그 추가'},'＋');row.append(input,button);row.onsubmit=e=>{e.preventDefault();const t=input.value.trim();if(!t)return;if(g.options.includes(t)){toast('이미 있는 태그입니다.');return}if(g.options.length>=12){toast('태그는 그룹당 12개까지 추가할 수 있습니다.');return}g.options.push(t);g.selected.push(t);renderTags();draw()};section.append(row)}root.append(section)})}
function line(x,y,x2,y2,color='#343841',width=1){ctx.beginPath();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke()}
function rect(x,y,w,h,fill,stroke){if(fill){ctx.fillStyle=fill;ctx.fillRect(x,y,w,h)}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.strokeRect(x+.5,y+.5,w-1,h-1)}}
function text(s,x,y,size=16,color='#c8cbd3',font=sans,weight=400){ctx.fillStyle=color;ctx.font=`${weight} ${size*state.fontScale/100}px ${font}`;ctx.textBaseline='top';ctx.fillText(String(s),x,y)}
function fitText(s,x,y,max,size=16,color='#d8dce4',font=sans,weight=400){let n=size;ctx.font=`${weight} ${n*state.fontScale/100}px ${font}`;while(ctx.measureText(s).width>max&&n>9){n-=.5;ctx.font=`${weight} ${n*state.fontScale/100}px ${font}`}text(s,x,y,n,color,font,weight)}
function wrapped(s,x,y,max,size=17,leading=29,color='#b8bec9'){ctx.font=`400 ${size*state.fontScale/100}px ${sans}`;let yy=y;for(const paragraph of s.split('\n')){let row='';for(const char of paragraph){if(ctx.measureText(row+char).width>max&&row){text(row,x,yy,size,color);yy+=leading;row=''}row+=char}text(row,x,yy,size,color);yy+=leading}return yy}
function measureLines(s,max,size=17){ctx.font=`400 ${size*state.fontScale/100}px ${sans}`;let count=0;for(const p of s.split('\n')){let row='';for(const ch of p){if(ctx.measureText(row+ch).width>max&&row){count++;row=''}row+=ch}count++}return count}
function bracket(x,y,w,h,color=state.accent){const n=13;[[x,y,1,1],[x+w,y,-1,1],[x,y+h,1,-1],[x+w,y+h,-1,-1]].forEach(([xx,yy,dx,dy])=>{line(xx,yy,xx+dx*n,yy,color,2);line(xx,yy,xx,yy+dy*n,color,2)})}
function addHit(x,y,w,h,kind,target){hits.push({x,y,w,h,kind,target})}
function polygon(points,fill,stroke,width=1){ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.lineWidth=width;ctx.strokeStyle=stroke;ctx.stroke()}}
function frame(x,y,w,h,fill=palette.panel,stroke=palette.line,cut=13){polygon([[x+cut,y],[x+w-30,y],[x+w-18,y+5],[x+w-6,y+5],[x+w,y+11],[x+w,y+h-cut],[x+w-cut,y+h],[x+24,y+h],[x+16,y+h-5],[x,y+h-5],[x,y+cut]],fill,stroke)}
function slashes(x,y,n=5,size=10,color=state.accent){for(let i=0;i<n;i++)polygon([[x+i*9,y],[x+i*9+5,y],[x+i*9+5-size*.55,y+size],[x+i*9-size*.55,y+size]],color)}
function heading(n,s,x,y,w){polygon([[x,y],[x+24,y],[x+31,y+10],[x+24,y+22],[x,y+22]],state.accent);text(n,x+5,y+4,11,palette.light?'#ffffff':'#07141a',mono,600);fitText(s,x+41,y+3,w-114,14,palette.ink,mono,600);line(x+40,y+27,x+w-51,y+27,palette.line);line(x+w-51,y+27,x+w-39,y+17,palette.line);line(x+w-39,y+17,x+w,y+17,palette.line);slashes(x+w-37,y+3,4,7)}
function imageBox(item,x,y,w,h,key,number){rect(x,y,w,h,palette.surface,palette.line);ctx.save();ctx.beginPath();ctx.rect(x+1,y+1,w-2,h-2);ctx.clip();if(item.img){const ratio=Math.max(w/item.img.width,h/item.img.height)*item.zoom;const iw=item.img.width*ratio,ih=item.img.height*ratio;const dx=Math.max(-(iw-w)/2,Math.min((iw-w)/2,item.dx*w)),dy=Math.max(-(ih-h)/2,Math.min((ih-h)/2,item.dy*h));if(state.mono)ctx.filter='grayscale(1)';ctx.drawImage(item.img,x+(w-iw)/2+dx,y+(h-ih)/2+dy,iw,ih);ctx.filter='none'}else{ctx.strokeStyle=palette.line;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+w,y+h);ctx.moveTo(x+w,y);ctx.lineTo(x,y+h);ctx.stroke();rect(x+w/2-26,y+h/2-26,52,52,palette.surface);line(x+w/2-10,y+h/2,x+w/2+10,y+h/2,palette.muted);line(x+w/2,y+h/2-10,x+w/2,y+h/2+10,palette.muted);ctx.textAlign='center';text(key==='avatar'?'프로필 이미지':'이미지 업로드',x+w/2,y+h/2+34,14,palette.muted);ctx.textAlign='left';text(number||'ID / 001',x+13,y+12,11,palette.dim,mono)}ctx.restore();if(item.showCaption&&(item.title||item.caption)){const gh=76;const gradient=ctx.createLinearGradient(0,y+h-gh,0,y+h);gradient.addColorStop(0,'#090b0e00');gradient.addColorStop(.35,'#090b0ecc');gradient.addColorStop(1,'#090b0eee');rect(x,y+h-gh,w,gh,gradient);fitText(item.title,x+14,y+h-53,w-28,17,'#fff',sans,600);fitText(item.caption,x+14,y+h-28,w-28,13,'#bdc3ce')}frame(x-5,y-5,w+10,h+10,null,state.accent,12);line(x+15,y-7,x+w*.52,y-7,state.accent,2);slashes(x+w-44,y+h+3,4,5);addHit(x,y,w,h,'image',key)}
function drawTags(g,x,y,max){text(g.label.toUpperCase(),x,y,12,palette.muted,mono);let xx=x,yy=y+25;g.options.forEach(t=>{ctx.font=`400 ${14*state.fontScale/100}px ${sans}`;let tw=ctx.measureText(t).width+24;if(xx+tw>x+max){xx=x;yy+=37}const selected=g.selected.includes(t);polygon([[xx+6,yy],[xx+tw,yy],[xx+tw,yy+22],[xx+tw-6,yy+28],[xx,yy+28],[xx,yy+6]],selected?state.accent+'28':palette.surface,selected?state.accent:palette.line);text(t,xx+12,yy+5,14,selected?state.accent:palette.muted);addHit(xx,yy,tw,28,'tag',{group:g.id,value:t});xx+=tw+7});return yy+45}
function tagHeight(g,max){let xx=0,rows=1;g.options.forEach(t=>{ctx.font=`400 ${14*state.fontScale/100}px ${sans}`;const tw=ctx.measureText(t).width+24;if(xx+tw>max){rows++;xx=0}xx+=tw+7});return 70+(rows-1)*37}
function draw(){
palette=colors();const p=state.layout==='portrait';W=p?800:1200;
const noteW=p?338:288,tagW=p?365:288;
const noteH=Math.max(124,60+Math.max(measureLines(state.info,noteW-32),measureLines(state.ng,noteW-32))*29);
const tagsH=state.groups.reduce((sum,g)=>sum+tagHeight(g,tagW),0);
const genreH=Math.max(70,28+measureLines(state.genre,tagW-28,15)*25);
const upperH=Math.max(p?296:308,tagsH+genreH+64),notesY=244+upperH;
const rows=Math.ceil(state.gallery.length/2),galleryH=rows*(p?226:247);
const gy=p?notesY+noteH+115:215;
H=p?gy+galleryH+120:Math.max(850,notesY+noteH+180,gy+galleryH+130);
canvas.width=W*2;canvas.height=H*2;ctx.setTransform(2,0,0,2,0,0);hits=[];
const bg=ctx.createLinearGradient(0,0,W,H);bg.addColorStop(0,state.bg1);bg.addColorStop(1,state.bg2);rect(0,0,W,H,bg);
if(state.grid){for(let x=0;x<W;x+=32)line(x,0,x,H,palette.grid);for(let y=0;y<H;y+=32)line(0,y,W,y,palette.grid);for(let x=64;x<W;x+=128)for(let y=64;y<H;y+=128){line(x-2,y,x+2,y,palette.line,.5);line(x,y-2,x,y+2,palette.line,.5)}}
// A multi-layer, chamfered instrument housing surrounds the actual profile.
const outer=[[32,8],[W-124,8],[W-106,19],[W-33,19],[W-8,44],[W-8,H-52],[W-34,H-26],[W-182,H-26],[W-196,H-12],[43,H-12],[12,H-43],[12,28]];
polygon(outer,null,state.accent,1.5);
polygon([[37,17],[W-130,17],[W-111,29],[W-39,29],[W-19,49],[W-19,H-57],[W-39,H-37],[W-187,H-37],[W-202,H-23],[48,H-23],[23,H-48],[23,34]],null,palette.line,1);
polygon([[39,8],[223,8],[211,16],[32,16]],state.accent);
polygon([[W-165,H-12],[W-61,H-12],[W-40,H-25],[W-151,H-25]],state.accent);
slashes(258,8,7,7);slashes(W-87,50,5,6);
line(14,164,23,173,state.accent,3);line(14,173,14,278,state.accent,3);line(W-14,H-245,W-14,H-130,state.accent,3);
for(let y=320;y<H-140;y+=22){line(13,y,18,y,palette.dim);line(W-18,y,W-13,y,palette.dim)}
for(const [x,y]of [[30,35],[W-30,49],[36,H-46],[W-32,H-52]]){ctx.strokeStyle=palette.muted;ctx.lineWidth=1;ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.stroke()}
text('PERSONAL DATA // 001',46,40,12,state.accent,mono,600);
const nameWidth=p?460:850;fitText(state.name||'YOUR NAME',46,82,nameWidth,47,palette.ink,mono,600);addHit(43,78,nameWidth,58,'field','name');
fitText(state.handle,48,141,p?444:785,16,state.accent,mono);addHit(45,136,p?445:790,30,'field','handle');
polygon([[43,183],[245,183],[257,175],[W-181,175],[W-169,186],[W-43,186],[W-43,192],[W-174,192],[W-188,182],[262,182],[250,191],[43,191]],state.accent+'25',palette.line);
line(44,184,230,184,state.accent,2);slashes(W-152,177,9,7);
const avatarW=p?278:268,avatarH=p?286:300;imageBox(state.avatar,46,222,avatarW,avatarH,'avatar');
const tx=p?359:348;let ty=224;state.groups.forEach(g=>{ty=drawTags(g,tx,ty,tagW)});fitText(state.farewell,tx,ty,tagW,12,palette.muted);addHit(tx,ty,tagW,24,'field','farewell');
const genreY=ty+38;text('장르',tx,genreY,12,palette.muted);frame(tx,genreY+24,tagW,genreH,palette.panel,palette.line,9);line(tx,genreY+40,tx,genreY+58,state.accent,2);if(state.genre)wrapped(state.genre,tx+14,genreY+38,tagW-28,15,25,palette.text);addHit(tx,genreY,tagW,genreH+24,'field','genre');
fitText(state.tagline,46,notesY-8,p?W-92:594,17,palette.ink,sans,500);addHit(44,notesY-12,p?W-88:596,28,'field','tagline');
fitText(state.contact,46,notesY+23,p?W-92:594,13,palette.muted);addHit(44,notesY+19,p?W-88:596,24,'field','contact');
const ny=notesY+65,nw=p?338:288;
[[46,state.info,'01','INFO','info'],[p?416:356,state.ng,'02','NG / NOTICE','ng']].forEach(([x,s,n,title,key])=>{heading(n,title,x,ny,nw);frame(x,ny+40,nw,noteH-20,palette.panel,palette.line);line(x+2,ny+58,x+2,ny+89,state.accent,2);wrapped(s,x+16,ny+54,nw-32,17,29,palette.text);addHit(x,ny,nw,noteH+20,'field',key)});
const gx=p?46:706,gw=p?708:448;heading('03',state.galleryTitle,gx,gy,gw);addHit(gx,gy,gw,31,'field','galleryTitle');
const cardW=(gw-23)/2,cardH=p?201:222;state.gallery.forEach((item,i)=>imageBox(item,gx+(i%2)*(cardW+23),gy+51+Math.floor(i/2)*(cardH+25),cardW,cardH,i,'FRAME / '+String(i+1).padStart(2,'0')));
if(!p){line(676,217,676,H-93,palette.line);line(672,217,680,217,state.accent,2);line(672,H-93,680,H-93,state.accent,2)}
line(47,H-73,196,H-73,palette.line);line(196,H-73,205,H-65,palette.line);line(205,H-65,W-48,H-65,palette.line);slashes(48,H-62,5,9);
text('SIGNAL / PROFILE',110,H-51,11,palette.muted,mono);fitText(state.credit||'PERSONAL ARCHIVE // END OF RECORD',p?319:665,H-50,p?W-366:W-712,11,palette.muted,state.credit?sans:mono);addHit(p?319:665,H-54,p?W-366:W-712,23,'field','credit');
state.stickers.forEach((s,i)=>{const sw=s.size,sh=sw*s.img.height/s.img.width,sx=s.x*W,sy=s.y*H;ctx.save();ctx.translate(sx,sy);ctx.rotate(s.rotation*Math.PI/180);ctx.drawImage(s.img,-sw/2,-sh/2,sw,sh);ctx.restore();addHit(sx-sw/2,sy-sh/2,sw,sh,'sticker',i)});
// One restrained signature block, aligned with the header and divider.
// Draw last so the creator credit remains legible above stickers.
const sigX=W-238,sigY=77,sigW=190,sigH=80;
rect(sigX,sigY,sigW,sigH,state.bg1);
line(sigX,sigY,sigX,sigY+sigH,palette.line);
line(sigX,sigY,sigX,sigY+18,state.accent,2);
text('MADE BY',sigX+18,sigY+8,11,palette.muted,mono);
text('@COLT',sigX+18,sigY+29,27,state.accent,mono);
line(sigX+18,sigY+71,sigX+sigW,sigY+71,palette.line);

$('dimensions').textContent=`${W} × ${H} PX`;$('scale-label').textContent=`PNG · ${W*2} × ${H*2}`;
}
function chooseUpload(target){pendingUpload=target;$('file-input').value='';$('file-input').click()}
async function receiveUpload(file){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)){toast('PNG, JPG, WEBP 이미지를 선택해 주세요.');return}if(file.size>10*1024*1024){toast('10MB 이하의 이미지를 선택해 주세요.');return}const target=pendingUpload;try{const source=URL.createObjectURL(file),img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=source});if(img.width*img.height>50000000){URL.revokeObjectURL(source);throw Error('too large')}if(target==='sticker'){if(state.stickers.length>=15){URL.revokeObjectURL(source);toast('스티커는 15개까지 추가할 수 있습니다.');return}state.stickers.push({img,src:source,x:.75,y:.25,size:130,rotation:0});renderStickers()}else{const item=target==='avatar'?state.avatar:state.gallery[target];if(!item){URL.revokeObjectURL(source);return}if(item.src)URL.revokeObjectURL(item.src);Object.assign(item,{img,src:source,zoom:1,dx:0,dy:0});renderImages()}draw();toast('이미지가 추가되었습니다.')}catch(e){toast('이미지를 읽지 못했습니다. 다른 이미지를 선택해 주세요.')}}
function range(label,min,max,value,oninput,step=1){const l=el('label',{},label),out=el('output',{},String(value)),r=el('input',{type:'range',min,max,step,value,'aria-label':label});r.oninput=()=>{out.value=r.value;oninput(Number(r.value));draw()};l.append(out,r);return l}
function imageTools(parent,item,key){parent.append(range('이미지 확대',1,3,item.zoom,v=>item.zoom=v,.05));const reset=el('button',{class:'outline full'},'위치·확대 초기화');reset.onclick=()=>{item.zoom=1;item.dx=item.dy=0;renderImages();draw()};parent.append(reset);const remove=el('button',{class:'quiet full'},'업로드 이미지 제거');remove.onclick=()=>{if(item.src)URL.revokeObjectURL(item.src);Object.assign(item,{img:null,src:'',zoom:1,dx:0,dy:0});renderImages();draw()};parent.append(remove)}
function renderImages(){const avatar=$('avatar-tools');avatar.replaceChildren();avatar.hidden=!state.avatar.img;if(state.avatar.img)imageTools(avatar,state.avatar,'avatar');$('upload-avatar').textContent=state.avatar.img?'프로필 이미지 변경':'＋ 프로필 이미지 업로드';$('image-count').textContent=`${state.gallery.length} / 8`;const root=$('gallery-controls');root.replaceChildren();state.gallery.forEach((item,i)=>{const box=el('div',{class:'image-item'}),head=el('div',{class:'item-head'});head.append(el('span',{},'FRAME / '+String(i+1).padStart(2,'0')));const actions=el('div');for(const [symbol,delta]of [['↑',-1],['↓',1]]){const b=el('button',{'aria-label':delta<0?'앞으로 이동':'뒤로 이동'},symbol);b.disabled=i+delta<0||i+delta>=state.gallery.length;b.onclick=()=>{[state.gallery[i],state.gallery[i+delta]]=[state.gallery[i+delta],state.gallery[i]];renderImages();draw()};actions.append(b)}const remove=el('button',{'aria-label':'이미지 칸 삭제'},'×');remove.onclick=()=>{if(item.src)URL.revokeObjectURL(item.src);state.gallery.splice(i,1);renderImages();draw()};actions.append(remove);head.append(actions);box.append(head);if(item.src)box.append(el('img',{src:item.src,alt:'이미지 '+(i+1)}));const upload=el('button',{class:'outline'},item.img?'이미지 변경':'＋ 이미지 업로드');upload.onclick=()=>chooseUpload(i);box.append(upload);for(const [key,label,limit]of [['title','장르 / 페어명',30],['caption','해시태그 / 설명',50]]){const l=el('label',{},label),input=el('input',{maxlength:limit,value:item[key],placeholder:label});input.oninput=()=>{item[key]=input.value;draw()};l.append(input);box.append(l)}const l=el('label',{class:'check'}),check=el('input',{type:'checkbox'});check.checked=item.showCaption;check.onchange=()=>{item.showCaption=check.checked;draw()};l.append(check,document.createTextNode('캡션 표시'));box.append(l);if(item.img)imageTools(box,item,i);root.append(box)});$('add-image').disabled=state.gallery.length>=8}
function renderStickers(){const root=$('sticker-controls');root.replaceChildren();state.stickers.forEach((s,i)=>{const box=el('div',{class:'sticker-item'}),head=el('div',{class:'item-head'});head.append(el('span',{},'STICKER / '+String(i+1).padStart(2,'0')));const remove=el('button',{'aria-label':'스티커 삭제'},'×');remove.onclick=()=>{URL.revokeObjectURL(s.src);state.stickers.splice(i,1);renderStickers();draw()};head.append(remove);box.append(head);box.append(range('크기',40,500,s.size,v=>s.size=v),range('가로 위치 (%)',0,100,Math.round(s.x*100),v=>s.x=v/100),range('세로 위치 (%)',0,100,Math.round(s.y*100),v=>s.y=v/100),range('회전 (°)',-180,180,s.rotation,v=>s.rotation=v));root.append(box)})}
function point(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
function hit(p){return [...hits].reverse().find(h=>p.x>=h.x&&p.x<=h.x+h.w&&p.y>=h.y&&p.y<=h.y+h.h)}
canvas.addEventListener('pointerdown',e=>{const p=point(e),h=hit(p);if(!h)return;const item=h.kind==='sticker'?state.stickers[h.target]:h.kind==='image'?(h.target==='avatar'?state.avatar:state.gallery[h.target]):null;drag={h,start:p,last:p,moved:false,item};if(item&&(h.kind==='sticker'||item.img)){canvas.setPointerCapture(e.pointerId);canvas.style.cursor='grabbing'}});
canvas.addEventListener('pointermove',e=>{const p=point(e);if(!drag){const h=hit(p);canvas.style.cursor=h?(h.kind==='image'||h.kind==='sticker'?'grab':'pointer'):'default';return}const d=drag;const dx=p.x-d.last.x,dy=p.y-d.last.y;if(Math.abs(p.x-d.start.x)+Math.abs(p.y-d.start.y)>5)d.moved=true;if(d.moved&&d.item){if(d.h.kind==='sticker'){d.item.x=Math.max(0,Math.min(1,d.item.x+dx/W));d.item.y=Math.max(0,Math.min(1,d.item.y+dy/H))}else if(d.item.img){const r=Math.max(d.h.w/d.item.img.width,d.h.h/d.item.img.height)*d.item.zoom;const mx=(d.item.img.width*r/d.h.w-1)/2,my=(d.item.img.height*r/d.h.h-1)/2;d.item.dx=Math.max(-mx,Math.min(mx,d.item.dx+dx/d.h.w));d.item.dy=Math.max(-my,Math.min(my,d.item.dy+dy/d.h.h))}draw()}d.last=p});
canvas.addEventListener('pointerup',e=>{if(!drag)return;const {h,moved}=drag;if(!moved){if(h.kind==='image'){tab('images');chooseUpload(h.target)}else if(h.kind==='sticker'){tab('stickers')}else if(h.kind==='field'){tab('profile');const input=$(h.target);input.focus();input.scrollIntoView({behavior:'smooth',block:'nearest'});input.select()}else if(h.kind==='tag'){const g=state.groups.find(x=>x.id===h.target.group),v=h.target.value;g.selected=g.single?(g.selected.includes(v)?[]:[v]):g.selected.includes(v)?g.selected.filter(t=>t!==v):[...g.selected,v];renderTags();draw()}}if(h.kind==='sticker')renderStickers();drag=null;canvas.style.cursor='default';if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId)});
canvas.addEventListener('pointercancel',()=>{drag=null;canvas.style.cursor='default'});
canvas.addEventListener('wheel',e=>{const h=hit(point(e));if(!h||!['image','sticker'].includes(h.kind))return;const item=h.kind==='sticker'?state.stickers[h.target]:h.target==='avatar'?state.avatar:state.gallery[h.target];if(!item.img)return;e.preventDefault();if(h.kind==='sticker'){item.size=Math.max(40,Math.min(500,item.size-e.deltaY*.15));renderStickers()}else{item.zoom=Math.max(1,Math.min(3,item.zoom-e.deltaY*.002));renderImages()}draw()},{passive:false});
for(const key of ['name','handle','tagline','contact','farewell','genre','info','ng','galleryTitle','credit'])$(key).addEventListener('input',e=>{state[key]=e.target.value;draw()});
for(const key of ['accent','bg1','bg2']){const set=value=>{state[key]=value;$(key).value=value;$(key+'-hex').value=value.toUpperCase();updateChrome();renderThemes();draw()};$(key).oninput=e=>set(e.target.value);$(key+'-hex').onchange=e=>{let v=e.target.value.trim();if(!v.startsWith('#'))v='#'+v;if(/^#[0-9a-f]{6}$/i.test(v))set(v);else{e.target.value=state[key].toUpperCase();toast('6자리 HEX 색상을 입력해 주세요.')}}}
document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{$('accent').value=b.dataset.color;$('accent').dispatchEvent(new Event('input'))});
for(const key of ['grid','mono'])$(key).onchange=e=>{state[key]=e.target.checked;draw()};$('fontScale').oninput=e=>{state.fontScale=Number(e.target.value);$('font-value').value=state.fontScale+'%';draw()};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));document.querySelectorAll('[data-layout]').forEach(b=>b.onclick=()=>setLayout(b.dataset.layout));
$('upload-avatar').onclick=()=>chooseUpload('avatar');$('upload-sticker').onclick=()=>chooseUpload('sticker');$('file-input').onchange=e=>receiveUpload(e.target.files[0]);$('add-image').onclick=()=>{if(state.gallery.length>=8)return;state.gallery.push(emptyImage());renderImages();draw()};
$('reset-colors').onclick=()=>{applyTheme(state.theme);toast('선택한 테마의 기본 색상으로 복원했습니다.')};
$('help').onclick=()=>$('help-dialog').showModal();document.querySelectorAll('.dialog-close').forEach(b=>b.onclick=()=>$('help-dialog').close());$('reset').onclick=()=>$('reset-dialog').showModal();$('cancel-reset').onclick=()=>$('reset-dialog').close();$('confirm-reset').onclick=()=>{[state.avatar,...state.gallery,...state.stickers].forEach(i=>{if(i.src)URL.revokeObjectURL(i.src)});state=initial();syncFields();$('reset-dialog').close();toast('새 자기소개표를 시작합니다.')};
let fontPromise=null;
function ensureFont(){
 if(!fontPromise){fontPromise=(async()=>{
  let timer;
  try {
   const faces=await Promise.race([
    document.fonts.load('16px "D2Coding"','가나다 ABC 123'),
    new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('font')),15000)})
   ]);
   if(!faces.length||!document.fonts.check('16px "D2Coding"','가나다'))throw new Error('font');
  }catch(e){fontPromise=null;throw new Error('font');}finally{clearTimeout(timer);}
 })();}
 return fontPromise;
}
$('export').onclick=async()=>{const button=$('export');button.disabled=true;try{await ensureFont();draw();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('export');const url=URL.createObjectURL(blob),a=el('a',{href:url,download:`SIGNAL_${(state.name||'profile').replace(/[^a-zA-Z0-9가-힣_-]/g,'_')}_${state.layout}.png`});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);toast('PNG를 저장했습니다.')}catch(e){toast(e.message==='font'?'D2Coding을 불러오지 못했습니다. 인터넷 연결을 확인한 후 다시 저장할 수 있습니다.':'저장하지 못했습니다. 이미지 수를 줄여 다시 시도해 주세요.')}finally{button.disabled=false}};
syncFields();
ensureFont().then(()=>draw()).catch(()=>toast('D2Coding을 불러오지 못했습니다. 인터넷 연결 확인이 필요합니다.'));
